### ISSUE TITLE
make serve 需要安装什么东西吗？提示无法识别为可运行的程序

### ISSUE THREAD

**Issue by Scheelite36** [PegasusWang/python-web-guide#9]
如题

**Comment by PegasusWang** [comment]
`pip install -r requirements.txt` 执行了么？

**Comment by Scheelite36** [comment]
> `pip install -r requirements.txt` 执行了么？

已执行，按着方式二的步骤来的，在项目目录下执行的

**Comment by PegasusWang** [comment]
是在 linux 下么？ 能发一下具体的报错信息么？我试了一下没问题。 makefile 看着也是没问题的，最近也在零散更新

**Comment by Scheelite36** [comment]
> 是在 linux 下么？ 能发一下具体的报错信息么？我试了一下没问题。 makefile 看着也是没问题的，最近也在零散更新

windows下的

make : 无法将“make”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确
，然后再试一次。
所在位置 行:1 字符: 1
`+ make serve`
`+ ~~~~`
  `  + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException`
    `+ FullyQualifiedErrorId : CommandNotFoundException`

**Comment by PegasusWang** [comment]
windows 可能需要安装 make
